kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "perftest-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/bmarolleau/auto-perf-test.git"
    contextDir: jenkins
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipelines/Jenkinsfile
