kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "perftest-pipeline"
spec:
  source:
    git:
      uri: https://github.com/bmarolleau/acmeair-customerservice-java-jdbc.git
    contextDir: "perftest/jenkins"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipelines/Jenkinsfile
