--  Generate SQL 
--  Version:                   	V7R3M0 160422 
--  Generated on:              	12/10/20 14:46:00 
--  Relational Database:       	O01DD6F4 
--  Standards Option:          	Db2 for i 
CREATE TABLE ACMEAIR.AIRPORTCODEMAPPING FOR SYSTEM NAME AIRPO00001 ( 
	"ID" CHAR(3) CCSID 37 NOT NULL , 
	NAME VARCHAR(20) CCSID 37 DEFAULT NULL , 
	CONSTRAINT ACMEAIR.Q_ACMEAIR_AIRPO00001_ID_00001 PRIMARY KEY( "ID" ) )   
	  
	RCDFMT AIRPO00001 ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON ACMEAIR.AIRPORTCODEMAPPING TO QSECOFR WITH GRANT OPTION ; 
  
  
CREATE TABLE ACMEAIR.BOOKING ( 
	"ID" VARCHAR(40) CCSID 37 NOT NULL , 
	CUSTOMERID VARCHAR(20) CCSID 37 DEFAULT NULL , 
	FLIGHTID VARCHAR(40) CCSID 37 DEFAULT NULL , 
	FLIGHTSEGMENTID FOR COLUMN FLIGH00001 VARCHAR(6) CCSID 37 DEFAULT NULL , 
	DATEOFBOOKING FOR COLUMN DATEO00001 TIMESTAMP DEFAULT NULL , 
	CONSTRAINT ACMEAIR.Q_ACMEAIR_BOOKING_ID_00001 PRIMARY KEY( "ID" ) )   
	  
	RCDFMT BOOKING    ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON ACMEAIR.BOOKING TO QSECOFR WITH GRANT OPTION ; 
  
  
CREATE TABLE ACMEAIR.CUSTOMER ( 
	"ID" VARCHAR(20) CCSID 37 NOT NULL , 
	"PASSWORD" VARCHAR(20) CCSID 37 DEFAULT NULL , 
	STATUS VARCHAR(10) CCSID 37 DEFAULT NULL , 
	TOTAL_MILES FOR COLUMN TOTAL00001 INTEGER DEFAULT NULL , 
	MILES_YTD INTEGER DEFAULT NULL , 
	PHONENUMBER FOR COLUMN PHONE00001 VARCHAR(15) CCSID 37 DEFAULT NULL , 
	PHONENUMBERTYPE FOR COLUMN PHONE00002 VARCHAR(10) CCSID 37 DEFAULT NULL , 
	STREETADDRESS1 FOR COLUMN STREE00001 VARCHAR(20) CCSID 37 DEFAULT NULL , 
	STREETADDRESS2 FOR COLUMN STREE00002 VARCHAR(20) CCSID 37 DEFAULT NULL , 
	CITY VARCHAR(20) CCSID 37 DEFAULT NULL , 
	STATEPROVINCE FOR COLUMN STATE00001 VARCHAR(20) CCSID 37 DEFAULT NULL , 
	COUNTRY VARCHAR(20) CCSID 37 DEFAULT NULL , 
	POSTALCODE VARCHAR(10) CCSID 37 DEFAULT NULL , 
	CONSTRAINT ACMEAIR.Q_ACMEAIR_CUSTOMER_ID_00001 PRIMARY KEY( "ID" ) )   
	  
	RCDFMT CUSTOMER   ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON ACMEAIR.CUSTOMER TO QSECOFR WITH GRANT OPTION ; 
  
  
CREATE TABLE ACMEAIR.CUSTOMERSESSION FOR SYSTEM NAME CUSTO00001 ( 
	"ID" VARCHAR(40) CCSID 37 NOT NULL , 
	CUSTOMERID VARCHAR(20) CCSID 37 DEFAULT NULL , 
	LASTACCESSEDTIME FOR COLUMN LASTA00001 TIMESTAMP DEFAULT NULL , 
	TIMEOUTTIME FOR COLUMN TIMEO00001 TIMESTAMP DEFAULT NULL , 
	CONSTRAINT ACMEAIR.Q_ACMEAIR_CUSTO00001_ID_00001 PRIMARY KEY( "ID" ) )   
	  
	RCDFMT CUSTO00001 ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON ACMEAIR.CUSTOMERSESSION TO QSECOFR WITH GRANT OPTION ; 
  
  
CREATE TABLE ACMEAIR.FLIGHT ( 
	"ID" VARCHAR(40) CCSID 37 NOT NULL , 
	FLIGHTSEGMENTID FOR COLUMN FLIGH00001 VARCHAR(6) CCSID 37 DEFAULT NULL , 
	SCHEDULEDDEPARTURETIME FOR COLUMN SCHED00001 TIMESTAMP DEFAULT NULL , 
	SCHEDULEDARRIVALTIME FOR COLUMN SCHED00002 TIMESTAMP DEFAULT NULL , 
	FIRSTCLASSBASECOST FOR COLUMN FIRST00001 NUMERIC(8, 2) DEFAULT NULL , 
	ECONOMYCLASSBASECOST FOR COLUMN ECONO00001 NUMERIC(8, 2) DEFAULT NULL , 
	NUMFIRSTCLASSSEATS FOR COLUMN NUMFI00001 INTEGER DEFAULT NULL , 
	NUMECONOMYCLASSSEATS FOR COLUMN NUMEC00001 INTEGER DEFAULT NULL , 
	AIRPLANETYPEID FOR COLUMN AIRPL00001 VARCHAR(10) CCSID 37 DEFAULT NULL , 
	CONSTRAINT ACMEAIR.Q_ACMEAIR_FLIGHT_ID_00001 PRIMARY KEY( "ID" ) )   
	  
	RCDFMT FLIGHT     ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON ACMEAIR.FLIGHT TO QSECOFR WITH GRANT OPTION ; 
  
  
CREATE TABLE ACMEAIR.FLIGHTSEGMENT FOR SYSTEM NAME FLIGH00001 ( 
	"ID" VARCHAR(6) CCSID 37 NOT NULL , 
	ORIGINPORT CHAR(3) CCSID 37 DEFAULT NULL , 
	DESTPORT CHAR(3) CCSID 37 DEFAULT NULL , 
	MILES INTEGER DEFAULT NULL , 
	CONSTRAINT ACMEAIR.Q_ACMEAIR_FLIGH00001_ID_00001 PRIMARY KEY( "ID" ) )   
	  
	RCDFMT FLIGH00001 ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON ACMEAIR.FLIGHTSEGMENT TO QSECOFR WITH GRANT OPTION ; 
  
  
CREATE TABLE ACMEAIR.PUSHMESSAGE FOR SYSTEM NAME PUSHM00001 ( 
	"ID" SMALLINT GENERATED ALWAYS AS IDENTITY ( 
	START WITH 1 INCREMENT BY 1 
	NO MINVALUE NO MAXVALUE 
	CYCLE NO ORDER 
	CACHE 20 ) 
	, 
	CUSTOMERID VARCHAR(100) CCSID 37 DEFAULT NULL , 
	MESSAGE VARCHAR(1000) CCSID 37 DEFAULT NULL , 
	STATUS VARCHAR(30) CCSID 37 DEFAULT NULL , 
	SENTSTATUS TIMESTAMP DEFAULT NULL , 
	CONSTRAINT ACMEAIR.Q_ACMEAIR_PUSHM00001_ID_00001 PRIMARY KEY( "ID" ) )   
	  
	RCDFMT PUSHM00001 ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON ACMEAIR.PUSHMESSAGE TO QSECOFR WITH GRANT OPTION ; 
  
  
CREATE TRIGGER ACMEAIR.BOOKING_MOBILEPUSH 
	AFTER INSERT OR DELETE OR UPDATE ON ACMEAIR.BOOKING 
	REFERENCING OLD AS O 
	NEW AS N 
	FOR EACH ROW 
	MODE DB2SQL 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = ACMEAIR , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
INSERT INTO ACMEAIR . PUSHMESSAGE ( CUSTOMERID , MESSAGE , STATUS ) VALUES ( 
CASE 
WHEN INSERTING OR UPDATING 
THEN N . CUSTOMERID 
WHEN DELETING 
THEN O . CUSTOMERID 
END , 
CASE 
WHEN INSERTING 
THEN 'ACME AIR Reservation for Flight ' || N . FLIGHTSEGMENTID || ' confirmed' WHEN UPDATING 
THEN 'ACME AIR Reservation for Flight ' || N . FLIGHTSEGMENTID || ' modified' 
WHEN DELETING 
THEN 'ACME AIR Reservation for Flight ' || O . FLIGHTSEGMENTID || ' cancelled' END 
, 
'initial' 
) ; 
END  ; 
  
